import { FieldType } from '../types/filter.types';
import type { FieldDefinition, OperatorLabels, FilterOperator } from '../types/filter.types';

/**
 * Filter Configuration
 * Defines all filterable fields with their types, operators, and options
 */

// Field definitions for all filterable columns
export const FIELD_DEFINITIONS: FieldDefinition[] = [
  // Text Fields
  {
    key: 'id',
    label: 'ID',
    type: FieldType.TEXT,
    operators: ['equals', 'contains', 'startsWith', 'endsWith', 'doesNotContain'],
  },
  {
    key: 'name',
    label: 'Name',
    type: FieldType.TEXT,
    operators: ['equals', 'contains', 'startsWith', 'endsWith', 'doesNotContain'],
  },
  {
    key: 'email',
    label: 'Email',
    type: FieldType.TEXT,
    operators: ['equals', 'contains', 'startsWith', 'endsWith', 'doesNotContain'],
  },
  {
    key: 'department',
    label: 'Department',
    type: FieldType.TEXT,
    operators: ['equals', 'contains', 'startsWith', 'endsWith', 'doesNotContain'],
  },
  // Number Fields
  {
    key: 'projects',
    label: 'Projects',
    type: FieldType.NUMBER,
    operators: ['equals', 'greaterThan', 'lessThan', 'greaterThanOrEqual', 'lessThanOrEqual'],
  },
  {
    key: 'performanceRating',
    label: 'Performance Rating',
    type: FieldType.NUMBER,
    operators: ['equals', 'greaterThan', 'lessThan', 'greaterThanOrEqual', 'lessThanOrEqual'],
  },
  // Date Fields
  {
    key: 'joinDate',
    label: 'Join Date',
    type: FieldType.DATE,
    operators: ['between'],
  },
  {
    key: 'lastReview',
    label: 'Last Review',
    type: FieldType.DATE,
    operators: ['between'],
  },
  // Amount Fields
  {
    key: 'salary',
    label: 'Salary',
    type: FieldType.AMOUNT,
    operators: ['between'],
  },
  // Single Select Fields
  {
    key: 'address.city',
    label: 'City',
    type: FieldType.SINGLE_SELECT,
    operators: ['is', 'isNot'],
    path: 'address.city',
    options: [
      'San Francisco',
      'Austin',
      'New York',
      'Seattle',
      'Los Angeles',
      'Chicago',
      'Boston',
      'Denver',
      'Miami',
      'Portland',
      'San Diego',
      'Nashville',
      'Phoenix',
      'Washington',
      'Dallas',
      'Minneapolis',
      'Raleigh',
      'Atlanta',
    ],
  },
  {
    key: 'role',
    label: 'Role',
    type: FieldType.MULTI_SELECT,
    operators: ['in', 'notIn'],
    options: [
      'Senior Developer',
      'Junior Developer',
      'Product Manager',
      'UX Designer',
      'Tech Lead',
      'Marketing Manager',
      'DevOps Engineer',
      'Sales Representative',
      'Full Stack Developer',
      'HR Manager',
      'Backend Developer',
      'UI Designer',
      'Mobile Developer',
      'Content Writer',
      'QA Engineer',
      'Sales Manager',
      'Data Engineer',
      'Associate Product Manager',
      'Frontend Developer',
      'Visual Designer',
      'Security Engineer',
      'Digital Marketing Specialist',
      'Machine Learning Engineer',
      'Recruiter',
      'Cloud Architect',
      'Developer',
      'Brand Manager',
      'Database Administrator',
      'Account Executive',
      'Site Reliability Engineer',
      'Marketing Analyst',
      'Interaction Designer',
      'HR Business Partner',
      'Talent Acquisition Specialist',
      'Motion Designer',
      'Enterprise Sales Executive',
      'Sales Development Representative',
      'API Developer',
      'Social Media Manager',
      'Infrastructure Engineer',
      'Technical Product Manager',
      'Design Lead',
    ],
  },
  // Multi-Select Fields
  {
    key: 'skills',
    label: 'Skills',
    type: FieldType.MULTI_SELECT,
    operators: ['in', 'notIn'],
    options: [
      'React',
      'TypeScript',
      'Node.js',
      'GraphQL',
      'JavaScript',
      'CSS',
      'Product Strategy',
      'Analytics',
      'Agile',
      'Figma',
      'User Research',
      'Prototyping',
      'Python',
      'Django',
      'AWS',
      'Docker',
      'Kubernetes',
      'SEO',
      'Content Marketing',
      'Terraform',
      'Jenkins',
      'Linux',
      'CRM',
      'Negotiation',
      'Client Relations',
      'MongoDB',
      'Express',
      'Recruitment',
      'Employee Relations',
      'HRIS',
      'Java',
      'Spring Boot',
      'PostgreSQL',
      'Redis',
      'Sketch',
      'Adobe XD',
      'Illustration',
      'Vue.js',
      'Jest',
      'Design Systems',
      'React Native',
      'iOS',
      'Android',
      'Swift',
      'Copywriting',
      'Social Media',
      'Selenium',
      'Cypress',
      'Test Automation',
      'Sales Strategy',
      'Team Leadership',
      'Spark',
      'Airflow',
      'SQL',
      'Kafka',
      'Product Analysis',
      'User Research',
      'Roadmapping',
      'Angular',
      'RxJS',
      'SCSS',
      'Penetration Testing',
      'Security Auditing',
      'OWASP',
      'Google Ads',
      'Facebook Ads',
      'TensorFlow',
      'PyTorch',
      'MLOps',
      'Talent Acquisition',
      'Interviewing',
      'ATS',
      'Go',
      'Microservices',
      'gRPC',
      'Data Analysis',
      'Stakeholder Management',
      'HTML',
      'Git',
      'User Interviews',
      'Usability Testing',
      'Ruby',
      'Rails',
      'Animation',
      'Framer',
      'Next.js',
      'Webpack',
      'Employee Relations',
      'HR Strategy',
      'Compensation',
      'Azure',
      'Cloud Architecture',
      'Go-to-Market',
      'Firebase',
      'Campaign Management',
      'Creative Direction',
      'MySQL',
      'Database Optimization',
      'Lead Generation',
      'Cold Calling',
      'Spring',
      'Hibernate',
      'Maven',
      'REST APIs',
      'Prometheus',
      'Grafana',
      'Tableau',
      'Excel',
      'After Effects',
      'Motion Graphics',
      'Contract Negotiation',
      'Account Management',
    ],
  },
  // Boolean Fields
  {
    key: 'isActive',
    label: 'Active Status',
    type: FieldType.BOOLEAN,
    operators: ['is'],
  },
];

// Operator labels for display
export const OPERATOR_LABELS: OperatorLabels = {
  // Text operators
  equals: 'Equals',
  contains: 'Contains',
  startsWith: 'Starts With',
  endsWith: 'Ends With',
  doesNotContain: 'Does Not Contain',
  // Number operators
  greaterThan: 'Greater Than',
  lessThan: 'Less Than',
  greaterThanOrEqual: 'Greater Than or Equal',
  lessThanOrEqual: 'Less Than or Equal',
  // Date operators
  between: 'Between',
  // Amount operators (same as date, but for amounts)
  // Select operators
  is: 'Is',
  isNot: 'Is Not',
  // Multi-select operators
  in: 'In',
  notIn: 'Not In',
};

// Helper function to get field definition by key
export const getFieldDefinition = (key: string): FieldDefinition | undefined => {
  return FIELD_DEFINITIONS.find((field) => field.key === key);
};

// Helper function to get operators for a field type
export const getOperatorsForFieldType = (fieldType: FieldType): FilterOperator[] => {
  const field = FIELD_DEFINITIONS.find((f) => f.type === fieldType);
  return field?.operators || [];
};

